[versions]
agp = "8.13.1"
kotlin = "2.2.21"
devtools-ksp = "2.3.3"

[libraries]
annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }
yukihookapi-api = { module = "com.highcapable.yukihookapi:api", version = "1.3.1" }
yukihookapi-ksp-xposed = { module = "com.highcapable.yukihookapi:ksp-xposed", version = "1.3.1" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version = "1.0.2" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version = "1.0.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
